# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class TestFemaleTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_femaleTest(self):
    # Test name: Female Test
    # Step # | name | target | value
    # 1 | open | /body-fat-calculator.html?ctype=metric&csex=f&cage=40&cweightlbs=152&cheightfeet=5&cheightinch=10.5&cneckfeet=1&cneckinch=7.5&cwaistfeet=3&cwaistinch=1.5&chipfeet=2&chipinch=10.5&cweightkgs=100&cheightmeter=189&cneckmeter=57&cwaistmeter=98&chipmeter=100&x=Calculate | 
    self.driver.get("https://www.calculator.net/body-fat-calculator.html?ctype=metric&csex=f&cage=40&cweightlbs=152&cheightfeet=5&cheightinch=10.5&cneckfeet=1&cneckinch=7.5&cwaistfeet=3&cwaistinch=1.5&chipfeet=2&chipinch=10.5&cweightkgs=100&cheightmeter=189&cneckmeter=57&cwaistmeter=98&chipmeter=100&x=Calculate")
    # 2 | store | female | gender
    self.vars["gender"] = "female"
    # 3 | if | ${gender} == 'female' | 
    if self.driver.execute_script("return (arguments[0] == \'female\')", self.vars["gender"]):
      # 4 | setWindowSize | 934x704 | 
      self.driver.set_window_size(934, 704)
      # 5 | click | css=input:nth-child(2) | 
      self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
      # 6 | click | name=cage | 
      self.driver.find_element(By.NAME, "cage").click()
      # 7 | type | name=cage | 40
      self.driver.find_element(By.NAME, "cage").send_keys("40")
      # 8 | click | name=cweightkgs | 
      self.driver.find_element(By.NAME, "cweightkgs").click()
      # 9 | type | name=cweightkgs | 100
      self.driver.find_element(By.NAME, "cweightkgs").send_keys("100")
      # 10 | click | id=cheightmeter | 
      self.driver.find_element(By.ID, "cheightmeter").click()
      # 11 | type | id=cheightmeter | 189
      self.driver.find_element(By.ID, "cheightmeter").send_keys("189")
      # 12 | click | id=cneckmeter | 
      self.driver.find_element(By.ID, "cneckmeter").click()
      # 13 | type | id=cneckmeter | 57
      self.driver.find_element(By.ID, "cneckmeter").send_keys("57")
      # 14 | click | id=cwaistmeter | 
      self.driver.find_element(By.ID, "cwaistmeter").click()
      # 15 | type | id=cwaistmeter | 98
      self.driver.find_element(By.ID, "cwaistmeter").send_keys("98")
      # 16 | click | id=chipmeter | 
      self.driver.find_element(By.ID, "chipmeter").click()
      # 17 | type | id=chipmeter | 100
      self.driver.find_element(By.ID, "chipmeter").send_keys("100")
      # 18 | click | name=x | 
      self.driver.find_element(By.NAME, "x").click()
      # 19 | click | css=.rightresult | 
      self.driver.find_element(By.CSS_SELECTOR, ".rightresult").click()
      # 20 | click | css=.verybigtext | 
      self.driver.find_element(By.CSS_SELECTOR, ".verybigtext").click()
      # 21 | assertText | xpath=//div[@id='content']/div[3]/p/font/b | Body Fat: 23.0%
      assert self.driver.find_element(By.XPATH, "//div[@id=\'content\']/div[3]/p/font/b").text == "Body Fat: 23.0%"
      # 22 | echo | Body fat result for female is 23.0% | 
      print("Body fat result for female is 23.0%")
      # 23 | end |  | 

  if __name__ == "__main__":
    test_femaleTest()
